FROM mcr.microsoft.com/dotnet/sdk:6.0
WORKDIR /app
COPY Server/WordleOff.Server.csproj Server/WordleOff.Server.csproj
RUN dotnet restore Server/WordleOff.Server.csproj
COPY . .
RUN dotnet publish -c Release -r linux-x64 --self-contained=true -p:IncludeAllContentForSelfExtract=true -p:PublishTrimmed=true -o /output
