// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WordleOff.Server.Hubs;

#nullable disable

namespace WordleOff.Server.Migrations
{
    [DbContext(typeof(WordleOffContext))]
    partial class WordleOffContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WordleOff.Server.Hubs.GameSession", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PastAnswers")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PlayerDataDictionary")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid");

                    b.HasKey("SessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("GameSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
